spring.application.name=sasms

spring.datasource.url=jdbc:postgresql://localhost:5432/sasms_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:your_database_password_here}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:MySuperSecretKeyThatIsAtLeast32Chars!}
jwt.expiration=86400000

#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.service-url.defaultZone=http://localhost:9096/eureka/
#eureka.instance.hostname=localhost

logging.level.org.springframework= DEBUG

spring.devtools.livereload.enabled=true

stripe.secret.key=${STRIPE_SECRET_KEY:your_stripe_secret_key_here}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.port=8080
